### ISSUE TITLE
Citation non fonctionnelle 

### ISSUE THREAD

**Issue by Skulls23** [Dim145/AnimeSearch#3]
Impossible de proposer une nouvelle citation. 
Lors de l'appui sur "Proposer" cette fenêtre s'affiche : 

![image](https://user-images.githubusercontent.com/69755541/129491039-a678717b-e68d-43d5-84d7-8fe2c63ba6ef.png)

J'ai pas pu tester avant, mais est ce que ca viendrait pas du changement de serveur ?

**Comment by Dim145** [comment]
En effet c’est a cause de ça et d’un oublie de ma part.Le pb est corrigé Dimitri DuboisEtudiant InfoL3 De : Florian BoireauEnvoyé le :dimanche 15 août 2021 21:57À : Dim145/AnimeSearchCc : SubscribedObjet :[Dim145/AnimeSearch] Citation non fonctionnelle (#3) Impossible de proposer une nouvelle citation.Lors de l'appui sur "Proposer" cette fenêtre s'affiche :<title>Resource not found</title> <style type="text/css"> </style> <script> setTimeout(function(){ window.location.href = 'https://freeasphosting.net'; }, 1000); </script> The resource you are looking for might have been removed or temporarily unavailable due to inactivity. Please contact support for assistance.SIGN UP for FREE ASP.NET Hosting with MS SQL and 5 GB Storage. J'ai pas pu tester avant, mais est ce que ca viendrait pas du changement de serveur ?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
